name: balkezes
favicon: null
layout_spectrum: 0.29054606426507235
typography_spectrum: 0.1389248836785555
title: söröket élesztünk. főleg.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#100604'
    - '#239f9c'
    - '#90c9be'
    - '#646054'
  brandStrength: 0.4933723683934659
  lightness: 0.25036508962512016
  saturation: 0.8005165322683752
  rhythmicContrast: 0.726750195492059
purpose: []
